import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import productsRouter from "./products.js";
import adminRouter from "./admin.js";
import authRouter from "./auth.js";
import cartRouter from "./cart.js";
import checkoutRouter from "./checkout.js";
import ordersRouter from "./orders.js";
import adminOrdersRouter from "./admin-orders.js";
import batchesRouter from "./batches.js";
import pickupEventsRouter from "./pickup-events.js";
import adminCustomersRouter from "./admin-customers.js";
import notifyMeRouter from "./notify-me.js";
import webhooksRouter from "./webhooks.js";
import storageRouter from "./storage.js";
import eggsRouter from "./eggs.js";
import productImagesRouter from "./product-images.js";
import expensesRouter from "./expenses.js";
import contactRouter from "./contact.js";
import adminCouponsRouter from "./admin-coupons.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(productsRouter);
router.use(productImagesRouter);
router.use(adminRouter);
router.use(authRouter);
router.use(cartRouter);
router.use(checkoutRouter);
router.use(ordersRouter);
router.use(adminOrdersRouter);
router.use(batchesRouter);
router.use(pickupEventsRouter);
router.use(adminCustomersRouter);
router.use(notifyMeRouter);
router.use(webhooksRouter);
router.use(storageRouter);
router.use(eggsRouter);
router.use(expensesRouter);
router.use(contactRouter);
router.use(adminCouponsRouter);

export default router;
